name: oh-my-zsh
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/oh-my-zsh/**
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04-arm
          - macos-15
          - macos-15-intel
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    env:
      CELLAR_SERVER: ${{ secrets.CELLAR_SERVER }}
      CELLAR_TOKEN: ${{ secrets.CELLAR_TOKEN }}
      CELLAR_CACHE_ID: ${{ secrets.CELLAR_CACHE_ID }}
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install current Bash on macOS
        if: runner.os == 'macOS'
        run: |
          command -v brew && brew install bash || true

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21
        if: matrix.os != 'macos-15-intel'
        with:
          determinate: false

      - name: Install Nix (Intel Mac)
        uses: DeterminateSystems/nix-installer-action@v21
        if: matrix.os == 'macos-15-intel'
        with:
          determinate: false
          source-tag: v3.12.2

      - name: Install cellarctl
        uses: jinxcappa/cellar-action@v1
        with:
          configure-nix: 'true'

      - name: Build and push
        run: cellarctl push --flake .#oh-my-zsh
